"use client";
import { useSearchParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
type Pedido={pedidoId:string;status:string;valorCentavos:number;moeda:string;expiraEm:string;pix:{qrCode?:string;qrCodeBase64?:string;copiaECola:string}};
export default function Checkout(){const q=useSearchParams(),[pedido,setPedido]=useState<Pedido|null>(null),[erro,setErro]=useState(""),[nome,setNome]=useState(""),[telefone,setTelefone]=useState(""),[documento,setDocumento]=useState("");
useEffect(()=>{fetch("/api/billing/orders/pending").then(r=>r.ok?r.json():null).then(x=>{if(x?.pedido)setPedido(x.pedido)}).catch(()=>{})},[]);
useEffect(()=>{if(!pedido||pedido.status!=="AGUARDANDO")return;const t=setInterval(()=>fetch(`/api/billing/orders/${pedido.pedidoId}`).then(r=>r.json()).then(x=>setPedido(p=>p?{...p,...x}:p)).catch(()=>{}),10000);return()=>clearInterval(t)},[pedido]);
async function enviar(e:FormEvent){e.preventDefault();setErro("");const r=await fetch("/api/billing/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planoId:q.get("planoId"),planoPrecoId:q.get("planoPrecoId"),nome,telefone,documento})});const x=await r.json().catch(()=>null);if(!r.ok){setErro(x?.error??"Não foi possível iniciar o pagamento.");return}setPedido(x)}
if(pedido)return <main className="min-h-screen bg-zinc-950 px-4 pt-24 text-white"><h1 className="text-2xl font-bold">Pagamento pendente</h1><p className="mt-2 text-zinc-400">Status: {pedido.status}</p><p className="mt-3 text-lg">{new Intl.NumberFormat("pt-BR",{style:"currency",currency:pedido.moeda}).format(pedido.valorCentavos/100)}</p>{pedido.pix.qrCodeBase64&&<img className="mt-6 h-56 w-56 bg-white p-2" alt="QR Code PIX" src={`data:image/png;base64,${pedido.pix.qrCodeBase64}`}/>}<textarea readOnly value={pedido.pix.copiaECola??""} className="mt-4 w-full rounded bg-zinc-800 p-3 text-xs"/><button className="mt-2 rounded bg-red-600 px-4 py-2" onClick={()=>navigator.clipboard.writeText(pedido.pix.copiaECola)}>Copiar PIX</button><p className="mt-4 text-sm text-zinc-400">Aguardando pagamento até {new Date(pedido.expiraEm).toLocaleString("pt-BR")}. O status é confirmado pelo servidor.</p></main>;
return <main className="min-h-screen bg-zinc-950 px-4 pt-24 text-white"><h1 className="text-2xl font-bold">Finalizar assinatura</h1><form onSubmit={enviar} className="mt-6 max-w-md space-y-3"><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome completo" className="w-full rounded bg-zinc-800 p-3"/><input value={telefone} onChange={e=>setTelefone(e.target.value)} placeholder="Telefone com DDD" className="w-full rounded bg-zinc-800 p-3"/><input value={documento} onChange={e=>setDocumento(e.target.value)} placeholder="CPF ou CNPJ" className="w-full rounded bg-zinc-800 p-3"/>{erro&&<p className="text-red-300">{erro}</p>}<button className="rounded bg-red-600 px-5 py-3 font-semibold">Gerar PIX</button></form></main>}
