"use client";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { corpoCriarPedido, deveFazerPolling, mensagemErroCheckout, destinoDoLoginDoCheckout } from "@/lib/billing/checkout";
type Pendente={pedidoId:string;status:string;valorCentavos:number;moeda:string;expiraEm:string};
type Novo=Pendente&{pix:{qrCodeBase64?:string;copiaECola:string}};
type Pedido=Pendente|Novo;
type Selecao={plano:{id:string;nome:string};preco:{id:string;rotulo:string;duracaoDias:number;precoCentavos:number;moeda:string}};
const temPix=(p:Pedido):p is Novo=>"pix" in p;
const moeda=(v:number,m:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:m}).format(v/100);
// O total exibido é o do `PlanoPreco` escolhido, lido do catálogo público. O
// servidor recalcula tudo: cupom, adicionais e valor enviados daqui não são
// autoridade. Cupom e adicionais não têm regra aprovada e são recusados.
function CheckoutConteudo(){const q=useSearchParams();const router=useRouter();const{status}=useSession();const[pedido,setPedido]=useState<Pedido|null>(null);const[selecao,setSelecao]=useState<Selecao|null>(null);const[erro,setErro]=useState("");const[carregando,setCarregando]=useState(true);const[confirmado,setConfirmado]=useState(false);const[nome,setNome]=useState("");const[telefone,setTelefone]=useState("");const[documento,setDocumento]=useState("");const[cupom,setCupom]=useState("");
// Sem sessão, o pedido seria recusado pelo servidor. Vai ao login e volta para
// este mesmo checkout, com plano e preço preservados na querystring.
useEffect(()=>{if(status==="unauthenticated")router.replace(destinoDoLoginDoCheckout(q.toString()))},[status,q,router]);
useEffect(()=>{if(status!=="authenticated")return;fetch("/api/billing/orders/pending").then(r=>r.ok?r.json():null).then(x=>{if(x?.pedido)setPedido(x.pedido)}).catch(()=>{}).finally(()=>setCarregando(false))},[status]);
useEffect(()=>{fetch("/api/billing/plans").then(r=>r.ok?r.json():null).then(x=>{const plano=x?.planos?.find((p:any)=>p.id===q.get("planoId"));const preco=plano?.precos?.find((p:any)=>p.id===q.get("planoPrecoId"));if(plano&&preco)setSelecao({plano,preco})}).catch(()=>{})},[q]);
useEffect(()=>{if(!pedido||!deveFazerPolling(pedido.status))return;const t=setInterval(()=>fetch(`/api/billing/orders/${pedido.pedidoId}`).then(r=>r.ok?r.json():null).then(x=>{if(x)setPedido(p=>p?{...p,...x}:p)}).catch(()=>{}),10000);return()=>clearInterval(t)},[pedido]);
useEffect(()=>{if(pedido?.status!=="PAGO")return;fetch("/api/billing/me").then(r=>r.ok?r.json():null).then(x=>setConfirmado(Boolean(x?.plano?.id&&x.plano.id===q.get("planoId")))).catch(()=>setConfirmado(false))},[pedido?.status,q]);
async function criar(e:FormEvent){e.preventDefault();setErro("");const r=await fetch("/api/billing/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpoCriarPedido(q.get("planoId"),q.get("planoPrecoId"),{nome,telefone,documento},{cupom}))});const x=await r.json().catch(()=>null);if(!r.ok){setErro(mensagemErroCheckout(x?.codigo));return}setPedido(x)}
if(carregando||status!=="authenticated")return <main className="min-h-screen bg-zinc-950 p-24 text-white">Carregando checkout…</main>;
if(pedido)return <main className="min-h-screen bg-zinc-950 px-4 pt-24 text-white"><h1 className="text-2xl font-bold">{pedido.status==="PAGO"?"Assinatura ativada":"Pagamento pendente"}</h1><p className="mt-2 text-zinc-400">Status: {pedido.status}</p><p className="mt-3 text-lg">{moeda(pedido.valorCentavos,pedido.moeda)}</p>{pedido.status==="PAGO"?<div className="mt-6"><p className="text-zinc-300">{confirmado?"Seu plano foi atualizado.":"Confirmando seu plano…"}</p><Link href="/conta" className="mt-4 inline-block rounded bg-red-600 px-4 py-2">Ir para minha conta</Link><Link href="/planos" className="ml-3 text-sm underline">Ver planos</Link></div>:temPix(pedido)?<><>{pedido.pix.qrCodeBase64&&<img className="mt-6 h-56 w-56 bg-white p-2" alt="QR Code PIX" src={`data:image/png;base64,${pedido.pix.qrCodeBase64}`}/>}</><textarea readOnly value={pedido.pix.copiaECola} className="mt-4 w-full rounded bg-zinc-800 p-3 text-xs"/><button className="mt-2 rounded bg-red-600 px-4 py-2" onClick={()=>navigator.clipboard.writeText(pedido.pix.copiaECola)}>Copiar PIX</button></>:<p className="mt-6 text-sm text-zinc-400">Já existe um pagamento pendente. Volte à sessão em que o PIX foi gerado ou aguarde a confirmação.</p>}<p className="mt-4 text-sm text-zinc-400">Expira em {new Date(pedido.expiraEm).toLocaleString("pt-BR")}. A confirmação vem do servidor.</p></main>;
return <main className="min-h-screen bg-zinc-950 px-4 pt-24 text-white"><h1 className="text-2xl font-bold">Finalizar assinatura</h1>{selecao&&<section className="mt-4 rounded bg-zinc-900 p-4"><p className="font-semibold">{selecao.plano.nome}</p><p>{moeda(selecao.preco.precoCentavos,selecao.preco.moeda)} · {selecao.preco.rotulo}</p><p className="mt-1 text-xs text-zinc-500">Total do período, confirmado pelo servidor ao gerar o PIX.</p></section>}<form onSubmit={criar} className="mt-6 max-w-md space-y-3"><input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Nome completo" autoComplete="name" className="w-full rounded bg-zinc-800 p-3"/><input value={telefone} onChange={e=>setTelefone(e.target.value)} placeholder="Telefone com DDD" autoComplete="tel" inputMode="tel" className="w-full rounded bg-zinc-800 p-3"/><input value={documento} onChange={e=>setDocumento(e.target.value)} placeholder="CPF ou CNPJ" inputMode="numeric" className="w-full rounded bg-zinc-800 p-3"/><input value={cupom} onChange={e=>setCupom(e.target.value)} placeholder="Cupom (opcional)" maxLength={64} autoCapitalize="characters" className="w-full rounded bg-zinc-800 p-3"/>{erro&&<p className="text-red-300">{erro}</p>}<button disabled={!selecao} className="rounded bg-red-600 px-5 py-3 font-semibold disabled:opacity-50">Gerar PIX</button></form></main>}

export default function CheckoutPage() {
  return <Suspense fallback={<main className="min-h-screen bg-zinc-950 p-24 text-white">Carregando checkout…</main>}><CheckoutConteudo /></Suspense>;
}
