-- The application is server-only (Prisma) and does not use Supabase Data API
-- access from the browser. Deny all direct PostgREST access, including future
-- objects, and keep RLS as defense in depth if grants are restored by mistake.

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

ALTER TABLE "Episodio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Filme" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FilmeGenero" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Genero" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Like" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PopularHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Saga" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Serie" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SerieGenero" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncMetric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WatchHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Watchlist" ENABLE ROW LEVEL SECURITY;
