"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { planoEscolhidoDaUrl } from "@/lib/billing/checkout";
type Preco={id:string;rotulo:string;duracaoDias:number;precoCentavos:number;moeda:string};
type Beneficio={texto:string;incluido:boolean};
type Plano={id:string;nome:string;descricao:string|null;precos:Preco[];compravel:boolean;vitrine?:{selo:string|null;beneficios:Beneficio[]}};
type Me={plano:{id:string};assinatura:{status:string;terminaEm:string}|null};
const valor=(n:number,m:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:m}).format(n/100);
// Benefícios e preços vêm de `/api/billing/plans` — a mesma vitrine que a TV
// usa. Esta página não tem lista própria de benefícios.
// `?plano=<id>` vem do QR da TV. Só destaca o card: preço, compra e sessão
// continuam decididos pelo servidor. Lido do `window` para a página não precisar
// de Suspense só por isso.
export default function PlanosPage(){const[planos,setPlanos]=useState<Plano[]>([]),[me,setMe]=useState<Me|null>(null),[erro,setErro]=useState(false),[escolhido,setEscolhido]=useState<string|null>(null);useEffect(()=>{setEscolhido(planoEscolhidoDaUrl(window.location.search))},[]);useEffect(()=>{Promise.all([fetch("/api/billing/plans").then(r=>r.json()),fetch("/api/billing/me").then(r=>r.ok?r.json():null)]).then(([p,m])=>{setPlanos(p.planos);setMe(m)}).catch(()=>setErro(true))},[]);return <main className="min-h-screen bg-zinc-950 px-4 pb-16 pt-24 text-white md:px-10"><h1 className="text-3xl font-bold">Planos</h1>{erro?<p className="mt-8 text-red-300">Não foi possível carregar os planos.</p>:<div className="mt-8 grid gap-4 md:grid-cols-4">{planos.map(p=>{const atual=me?.plano.id===p.id,assinante=Boolean(me?.assinatura),daTv=escolhido===p.id&&!atual;return <section key={p.id} className={`rounded-2xl border bg-zinc-900 p-5 ${atual?"border-red-500":daTv?"border-amber-400":"border-zinc-800"}`}>{atual&&<p className="text-sm font-semibold text-red-400">Seu plano atual</p>}{daTv&&<p className="text-sm font-semibold text-amber-300">Plano escolhido na TV</p>}{p.vitrine?.selo&&<p className="text-xs font-bold uppercase tracking-wide text-zinc-300">{p.vitrine.selo}</p>}<h2 className="text-xl font-bold">{p.nome}</h2><ul className="my-5 space-y-1 text-sm">{(p.vitrine?.beneficios??[]).map(b=><li key={b.texto} className={b.incluido?"text-zinc-200":"text-zinc-500"}>{b.incluido?"✓ ":"– "}{b.texto}</li>)}</ul>{atual?<p className="text-sm text-zinc-400">Plano atual</p>:assinante?<p className="text-sm text-zinc-500">Você já possui uma assinatura ativa.</p>:p.compravel?p.precos.map(preco=><div key={preco.id} className="mt-3"><p>{valor(preco.precoCentavos,preco.moeda)}</p><p className="text-xs text-zinc-500">{preco.rotulo}</p><Link className="mt-2 block rounded-lg bg-red-600 px-4 py-2 text-center font-semibold" href={`/checkout?planoId=${p.id}&planoPrecoId=${preco.id}`}>Assinar</Link></div>):<p className="text-sm text-zinc-500">Plano temporariamente indisponível para compra.</p>}</section>})}</div>}</main>}
