import assert from "node:assert/strict";
import test from "node:test";
import { confirmarPedidoPorId } from "../billing/confirmacao";
import { criarFake, erroPrisma, pedido, AGORA } from "./helpers/billingConfirmacaoFake";

async function comFlag<T>(fn:()=>Promise<T>){const antes=process.env.BLACKCAT_CONFIRMACAO_ATIVA;process.env.BLACKCAT_CONFIRMACAO_ATIVA="true";try{return await fn()}finally{if(antes===undefined)delete process.env.BLACKCAT_CONFIRMACAO_ATIVA;else process.env.BLACKCAT_CONFIRMACAO_ATIVA=antes}}
test("injeta portas e usa snapshot com relógio fixo",async()=>comFlag(async()=>{const f=criarFake({pedido:pedido()});const r=await confirmarPedidoPorId("p",{prisma:f.banco,consultarStatusBlackcat:f.consultar,invalidarEntitlements:f.invalidar,agora:f.agora} as any);assert.equal(r.resultado,"ativar");assert.equal(f.estado.pedido.status,"PAGO");const a=f.estado.pedido.assinatura;assert.deepEqual([a.userId,a.planoId,a.planoPrecoId,a.pedidoId],["u","pl","pp","p"]);assert.equal(a.iniciaEm.toISOString(),AGORA.toISOString());assert.equal(a.terminaEm.toISOString(),"2026-10-10T12:00:00.000Z");assert.deepEqual(f.invalidacoes,["u"])}));
test("P2034 retenta uma vez e então confirma",async()=>comFlag(async()=>{const f=criarFake({pedido:pedido()},[erroPrisma("P2034")]);await confirmarPedidoPorId("p",{prisma:f.banco,consultarStatusBlackcat:f.consultar,invalidarEntitlements:f.invalidar,agora:f.agora} as any);assert.equal(f.transacoes(),2);assert.equal(f.estado.pedido.status,"PAGO")}));
test("P2034 para após três tentativas",async()=>comFlag(async()=>{const f=criarFake({pedido:pedido()},[erroPrisma("P2034"),erroPrisma("P2034"),erroPrisma("P2034")]);await assert.rejects(confirmarPedidoPorId("p",{prisma:f.banco,consultarStatusBlackcat:f.consultar,agora:f.agora} as any));assert.equal(f.transacoes(),3);assert.equal(f.estado.pedido.assinatura,null)}));
test("P2002 pedidoId coerente é idempotente",async()=>comFlag(async()=>{const p=pedido();const a={id:"a",userId:"u",planoId:"pl",planoPrecoId:"pp",pedidoId:"p",status:"ATIVA"};const f=criarFake({pedido:p,conflito:erroPrisma("P2002",["pedidoId"])});f.banco.$transaction=async(fn:any)=>{f.estado.pedido.status="PAGO";f.estado.pedido.assinatura=a;throw erroPrisma("P2002",["pedidoId"])};const r=await confirmarPedidoPorId("p",{prisma:f.banco,consultarStatusBlackcat:f.consultar,agora:f.agora} as any);assert.equal(r.resultado,"idempotente")}));
test("P2002 pedidoId incoerente revisa; outro unique propaga",async()=>comFlag(async()=>{const f=criarFake({pedido:pedido(),conflito:erroPrisma("P2002",["pedidoId"])});const r=await confirmarPedidoPorId("p",{prisma:f.banco,consultarStatusBlackcat:f.consultar,agora:f.agora} as any);assert.equal(r.resultado,"inconsistencia");const g=criarFake({pedido:pedido(),conflito:erroPrisma("P2002",["transacaoId"])});await assert.rejects(confirmarPedidoPorId("p",{prisma:g.banco,consultarStatusBlackcat:g.consultar,agora:g.agora} as any))}));
